### ISSUE TITLE
second stage

### ISSUE THREAD

**Issue by Lyan-ing** [THUDM/RelayDiffusion#1]
hi,  it is a good job.
i have some confusion for the network training, can you give me some suggestion:
can we input the natural images to the second stage when training the second network?
thank you!

**Comment by tengjiayan20** [comment]
Actually, when we train the second network, the input is natural images (you can see it in our training commands in README). The process of blurring images is contained in line 146 in "training/loss.py". You don’t need to preprocess images by yourself.

**Comment by Lyan-ing** [comment]
thank u very much!
Have you tried generating larger images, or larger upsampling factor( how to adapt the method)？

**Comment by tengjiayan20** [comment]
As illustrated in paper, actually, you just need to imitate the settings of 64->256 and go for a higher resolution. When we launch the super-resolution stage, the settings of diffusion the same as the first stage except for the size of unet. So when you try a higher resolution, you can adopt the same setting. As for the truncation point of noise schedule mentioned in Appendix A.2, its selection is not sensitive which we have conducted experiments.

**Comment by Lyan-ing** [comment]
ok, got it!
thank you!

**Comment by tengjiayan20** [comment]
We have updated the settings on 512 and 1024 models. It could be seen in Appendix C in OpenReview's version.
