### ISSUE TITLE
can not find file

### ISSUE THREAD

**Issue by yanre-hyd** [THUDM/RelayDiffusion#2]
Hello, thank you very much for your sharing, I would like to ask, when I ran the first command in Inference&Evaluation section, an error occurred, "net_first" was empty, and no files in ".pkl" or ".pt" format were found, where is this?

**Comment by tengjiayan20** [comment]
You can download the ckpt of model from the link in "Performance Reproduction" section, where both the first and the second stage model can be found.

**Comment by yanre-hyd** [comment]
Thank you! But is there any way to train a model with the data you provide？

**Comment by tengjiayan20** [comment]
We provide the training settings in "Training" section (at the bottom of the page).

**Comment by yanre-hyd** [comment]
Ok, so I need to go through the model after training and then do the Inference&Evaluation section?

**Comment by tengjiayan20** [comment]
If you want to train the model by yourself, you need to train it first. Or if you just want to generate images using the model we provide, you could download ckpt from the link mentioned above. And then do the Inference&Evaluation section.

**Comment by yanre-hyd** [comment]
Ok, I just started to learn how to reproduce the work, and I don't understand many things, so thank you very much for your patience, thank you!
