### ISSUE TITLE
question about get_alpha_t

### ISSUE THREAD

**Issue by YehLi** [THUDM/RelayDiffusion#3]
Thanks for your great work. I want to train a diffusion model from 512 resolution to 1024 resolution. However, the output size of alpha_next = get_alpha_t(...) does not match the size of u_cur. It seems that some parameters of get_alpha_t should be changed. How to change the parameter of get_alpha_t?

**Comment by tengjiayan20** [comment]
Sorry, it is our negligence that caused the code to be not universal enough. You can just set the parameter repeat_dims in ge t_alpha_t to "image_size//patch_size". In your experiment, it should be 1024//2.

**Comment by YehLi** [comment]
Thanks for your quick reply. I have another question. In training, the truncate_sigma is set to 7.5e-3 (in BlurLoss). During inference, the truncation_sigma is 0.9 (in blur_sampler). Does it matter? Should the truncate_sigma set to the same value?

**Comment by tengjiayan20** [comment]
Sorry, the variable naming brings ambiguity. The truncated sigma in train represents the lower limit of the sampled sigma, while the truncated sigma in inference represents the starting point (i.e., the maximum value) of the sigma during generation. It corresponds to the upper limit of the sampled sigma in train, but it is not completely equal.
