### ISSUE TITLE
About SNR

### ISSUE THREAD

**Issue by ShaochengShen** [THUDM/RelayDiffusion#4]

**Comment by tengjiayan20** [comment]
As stated in paper, the PSD analysis in our paper follows Rissanen et al "Generative modelling with inverse heat dissipation".
And we draw the SNR curves by modifying their codes. The code is in the attachment.
[psd.zip](https://github.com/THUDM/RelayDiffusion/files/13768223/psd.zip)

**Comment by ShaochengShen** [comment]
Tks a lot!
