### ISSUE TITLE
question about the reference dataset of FID on imagenet256

### ISSUE THREAD

**Issue by xtudbxk** [THUDM/RelayDiffusion#7]
Thanks for your wonderful work.

I am trying to reproduce your fid result on imagenet256. However, I encounter a problem when I generate the features of the whole training set of imagenet256 (about 1,281,167 images) using "python3 evaluation.py activations xxx" . It seems that the result .npz file is too large to save (maybe 20 GB or above). I also directly evaluate the fid using the statistics from guided-diffusion. But the fid is nearly 10, which is far away with your result. 

Thus, I wonder that which set you use for computing the reference statistics and could you release the generated mu/sigma using in your project ?

Thanks ~

**Comment by tengjiayan20** [comment]
The activation data of ImageNet is exactly very big. We have upload mu and sigma of ImageNet 256 for calculating FID only. As for your calculation of a larger FID, maybe due to some oversight?

**Comment by xtudbxk** [comment]
Thanks. 
The fid of the released ref and sample npz is the same with the paper ~
