### ISSUE TITLE
Missing the normalizer 1/sqrt(1+alpha^2) in Eq.(8)

### ISSUE THREAD

**Issue by WoodwindHu** [THUDM/RelayDiffusion#8]
Hello, thank you very much for your sharing. 
I noticed that the normalizer 1/sqrt(1+alpha^2) in Eq.(8) appers to be missing in the code:
https://github.com/THUDM/RelayDiffusion/blob/a97877fcee9e7515595e24f7d72bc5f6a722ce6f/training/loss.py#L149

Am I missing something, or is there a reason for this omission?
Thank you!

**Comment by tengjiayan20** [comment]
You are very careful!
Actually, we ignored this when we initially conducted experiments. This has little impact on our main experiment.
However, we realized this omission later and made amends, including both in paper and ablation study, for the sake of rigor.

**Comment by WoodwindHu** [comment]
Thanks.
